# Generated by Django 2.2.7 on 2020-08-08 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('subido_on', models.DateTimeField(auto_now=True)),
                ('contenido', models.TextField()),
                ('creado_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Edicion'), (1, 'Publicado')], default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Imagen')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_on'],
            },
        ),
    ]
